### ISSUE TITLE
Resetting default focus

### ISSUE THREAD

**Issue by endquote** [vovaguguiev/react-sunbeam#29]
When my app that uses Sunbeam starts, it's setting an item to focused by default. This is great.

When I change screens in my app using [react-navigation](https://reactnavigation.org), I'd like the first element on the new screen to be focused by default. However, the old item remains focused even though it's no longer visible, and maybe not even in the component tree anymore.

Is there a way to re-run the startup behavior to determine a new default focused element? I found `focusManager.revalidateFocusPath()`, but that didn't seem to do it.

**Comment by vovaguguiev** [comment]
Hi, are you sure that the old Focusable is not in the tree anymore, because it will stay focused if it's still there. If your use case requires the Focusable to stay in the tree but say invisible you could use `focusable: {false}` (https://github.com/vovaguguiev/react-sunbeam/blob/dc16272f336133baa7fedda7bb0f77ec919fe424/packages/react-sunbeam/src/focus/components/Focusable.tsx#L15) prop on it to make Sunbeam ignore it when it's not visible. Once changed to `false` it will trigger the re-selection of the new Focusable

**Comment by vovaguguiev** [comment]
Here is a practical example of how that prop can be used: https://github.com/vovaguguiev/react-sunbeam/blob/dc16272f336133baa7fedda7bb0f77ec919fe424/packages/demo/src/apps/SettingsMenu/Picker.tsx#L20

**Comment by endquote** [comment]
Thanks for the reply, and apologies for not seeing it sooner.

The old Focusable remains in the tree, but hidden, so it retains focus.

I hadn't noticed the focusable property, I'm guessing that will solve the problem. I'll explore and report back if that doesn't work.
